SELECT *
FROM
    VV_ORDER_ITEM
    INNER JOIN
    (
        SELECT ORDER_ID, ORDER_ITEM_SEQ_ID, SUM(QUANTITY) AS QUANTITY_SHIPPED
        FROM VV_SHIPMENT_ITEM
        GROUP BY ORDER_ID, ORDER_ITEM_SEQ_ID
    ) AS T1
        ON T1.ORDER_ID = VV_ORDER_ITEM.ORDER_ID AND T1.ORDER_ITEM_SEQ_ID = VV_ORDER_ITEM.ORDER_ITEM_SEQ_ID;






SELECT VO.ORDER_ID, T2.ORDER_ITEM_SEQ_ID, T2.PRODUCT_ID, T2.QUANTITY, T2.QUANTITY_SHIPPED
FROM
    (SELECT T1.ORDER_ID, T1.ORDER_ITEM_SEQ_ID, T1.QUANTITY_SHIPPED, T1.PRODUCT_ID, VI.QUANTITY
    FROM
        VV_ORDER_ITEM AS VI
        LEFT JOIN
        (
            SELECT VSI.ORDER_ID, VSI.PRODUCT_ID, VSI.ORDER_ITEM_SEQ_ID, SUM(QUANTITY) AS QUANTITY_SHIPPED
            FROM VV_SHIPMENT_ITEM AS VSI
            GROUP BY ORDER_ID, ORDER_ITEM_SEQ_ID
        ) AS T1
            ON T1.ORDER_ID = VI.ORDER_ID AND T1.ORDER_ITEM_SEQ_ID = VI.ORDER_ITEM_SEQ_ID) AS T2
	INNER JOIN
    VV_ORDER AS VO
    ON VO.ORDER_ID = T2.ORDER_ID;
