SELECT * 
FROM    
    (SELECT OS.ORDER_ID, OH.SHIP_BEFORE_DATE, OS.ORDER_ITEM_SEQ_ID, OS.PRODUCT_ID, PR.NAME, OS.QUANTITY, OS.QUANTITY_SHIPPED, OS.QUANTITY - OS.QUANTITY_SHIPPED AS QUANTITY_SHIPPABLE
    FROM
        (SELECT OI.ORDER_ID, OI.ORDER_ITEM_SEQ_ID, OI.PRODUCT_ID, OI.QUANTITY, SHI.QUANTITY_SHIPPED
        FROM
            VV_ORDER_ITEM AS OI
        LEFT JOIN
            (SELECT SI.ORDER_ID, SI.PRODUCT_ID, SI.ORDER_ITEM_SEQ_ID, SUM(QUANTITY) AS QUANTITY_SHIPPED
            FROM VV_SHIPMENT_ITEM AS SI
            WHERE ORDER_ID IS NOT NULL
            GROUP BY ORDER_ID, ORDER_ITEM_SEQ_ID) AS SHI
        ON SHI.ORDER_ID = OI.ORDER_ID AND SHI.ORDER_ITEM_SEQ_ID = OI.ORDER_ITEM_SEQ_ID) AS OS
    INNER JOIN
        VV_ORDER AS OH
    ON OH.ORDER_ID = OS.ORDER_ID
    INNER JOIN
        VV_PRODUCT AS PR
    ON PR.PRODUCT_ID = OS.PRODUCT_ID) AS VvOrderItemShippingItemView
WHERE QUANTITY_SHIPPABLE IS NULL OR QUANTITY_SHIPPABLE > 0;
