SELECT T3.NAME, SUM(T3.ORDWEIGHT),T3.SHIP_BEFORE_DATE 
FROM 
    (SELECT VV_PARTNER.NAME,T2.SHIP_BEFORE_DATE, T2.ORDER_ID, T2.QUANTITY * T2.WEIGHT AS ORDWEIGHT 
    FROM 
        (SELECT T1.ORDER_ID, T1.SHIP_BEFORE_DATE, T1.PRODUCT_ID,T1.PARTNER_ID,T1.QUANTITY,VV_PRODUCT.WEIGHT 
        FROM 
            (SELECT VV_ORDER.ORDER_ID,VV_ORDER.SHIP_BEFORE_DATE, PRODUCT_ID,PARTNER_ID,QUANTITY 
            FROM VV_ORDER 
            INNER JOIN VV_ORDER_ITEM 
            ON VV_ORDER.ORDER_ID = VV_ORDER_ITEM.ORDER_ID WHERE VV_ORDER.CREATED_STAMP > %s AND VV_ORDER.CREATED_STAMP < %s) AS T1 
        INNER JOIN VV_PRODUCT 
        ON VV_PRODUCT.PRODUCT_ID = T1.PRODUCT_ID) AS T2 
    INNER JOIN VV_PARTNER 
    ON VV_PARTNER.PARTNER_ID = T2.PARTNER_ID) AS T3 
GROUP BY T3.ORDER_ID
