SELECT VV_PARTNER.NAME,T2.NAME, T2.ORDER_ID, T2.QUANTITY 
FROM 
    (SELECT T1.ORDER_ID,T1.PRODUCT_ID,VV_PRODUCT.NAME, T1.PARTNER_ID,T1.QUANTITY,VV_PRODUCT.WEIGHT 
    FROM 
        (SELECT VV_ORDER.ORDER_ID,PRODUCT_ID,PARTNER_ID,QUANTITY 
        FROM VV_ORDER 
        INNER JOIN VV_ORDER_ITEM 
        ON VV_ORDER.ORDER_ID = VV_ORDER_ITEM.ORDER_ID 
        WHERE VV_ORDER.CREATED_STAMP > %s AND VV_ORDER.CREATED_STAMP < %s) AS T1 
    INNER JOIN VV_PRODUCT ON VV_PRODUCT.PRODUCT_ID = T1.PRODUCT_ID) AS T2 
INNER JOIN VV_PARTNER 
ON VV_PARTNER.PARTNER_ID = T2.PARTNER_ID
