WITH 
SHI (ORDER_ID, PRODUCT_ID, ORDER_ITEM_SEQ_ID, QUANTITY_SHIPPED ) AS (
    SELECT SI.ORDER_ID, SI.PRODUCT_ID, SI.ORDER_ITEM_SEQ_ID, SUM(QUANTITY) AS QUANTITY_SHIPPED
    FROM VV_SHIPMENT_ITEM AS SI
    WHERE ORDER_ID IS NOT NULL
    GROUP BY ORDER_ID, ORDER_ITEM_SEQ_ID   
),
OS (ORDER_ID, ORDER_ITEM_SEQ_ID, PRODUCT_ID, QUANTITY, QUANTITY_SHIPPED, QUANTITY_SHIPPABLE) AS (
    SELECT OI.ORDER_ID, OI.ORDER_ITEM_SEQ_ID, OI.PRODUCT_ID, OI.QUANTITY, SHI.QUANTITY_SHIPPED, OI.QUANTITY - SHI.QUANTITY_SHIPPED AS QUANTITY_SHIPPABLE
    FROM  
        VV_ORDER_ITEM AS OI
    LEFT JOIN 
        SHI
    ON 
        SHI.ORDER_ID = OI.ORDER_ID AND SHI.ORDER_ITEM_SEQ_ID = OI.ORDER_ITEM_SEQ_ID
)
SELECT OH.ORDER_ID, OH.SHIP_BEFORE_DATE, PR.NAME, OS.QUANTITY_SHIPPABLE, PR.WEIGHT, OS.QUANTITY, PART.NAME AS PARTNER_NAME, OH.ORDER_WEIGHT, OH.ORDER_NAME
FROM OS 
INNER JOIN
	VV_ORDER AS OH
ON 
	OH.ORDER_ID = OS.ORDER_ID
INNER JOIN
	VV_PRODUCT AS PR
ON 
	PR.PRODUCT_ID = OS.PRODUCT_ID
INNER JOIN
	VV_PARTNER AS PART
ON 
	PART.PARTNER_ID = OH.PARTNER_ID
WHERE QUANTITY_SHIPPABLE IS NULL OR QUANTITY_SHIPPABLE > 0
ORDER BY SHIP_BEFORE_DATE

